### ISSUE TITLE
API sorting

### ISSUE THREAD

**Issue by kimskimchi** [infrahq/infra#1341]
Results from `handlers.go`'s `ListProviders` should return alphabetically. This helps with the visualization on the user-facing areas.

**Comment by dnephin** [comment]
So far we have `data.ListGroups` and `data.ListIdentities` (aka ListUsers) sorting by `name ASC` (ascending).

**Comment by ssoroka** [comment]
I think the sort very much depends on the UI. IMO for sorting, APIs should:
- have a default sort, probably the default `id asc` because it's cheap and consistent between all endpoints regardless of what data it has (thus predictable).
- take a `sort` parameter that can do both ascending and descending ordering on any field. options are `sort=name+`/`sort=name-`, or `sort=name asc`/`sort=name desc`, or `sort=name&sortdirection=desc`.
- sorting should work with pagination, limit, offset, etc.
