### ISSUE TITLE
API case sensitivity

### ISSUE THREAD

**Issue by mchiang0610** [infrahq/infra#1554]
Currently: 

```
mchiang@Michaels-MacBook-Pro infra % ./infra providers remove Okta          
mchiang@Michaels-MacBook-Pro infra % ./infra providers list       
  NAME   URL                    
  infra                         
  okta   [redacted]  
```

**Comment by pdevine** [comment]
Just for reference:

Creating a container in Docker w/ mixed case in the name will result in a mixed case name:
```
$ docker run -it --rm -d --name HelloThere nginx
67ecb62d8ed01a1a8d45ccf63171ecbc36db8dcc4e8f98d0c79b27f8aa75eb39
$ docker ps
CONTAINER ID   IMAGE           COMMAND                  CREATED         STATUS         PORTS     NAMES
67ecb62d8ed0   nginx           "/docker-entrypoint.…"   4 seconds ago   Up 3 seconds   80/tcp    HelloThere
```
Here's what happens when you try to delete it:
```
$ docker kill hellothere
Error response from daemon: Cannot kill container: hellothere: No such container: hellothere
$ docker kill HelloThere
HelloThere
```

Kube requires you to type in the name as lowercase, and will fail if you don't meet the criteria:
```
$ kubectl create deployment HelloThere --namespace=hello --image=nginx
error: failed to create deployment: Deployment.apps "HelloThere" is invalid: metadata.name: Invalid value: "HelloThere": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Comment by pdevine** [comment]
To me the real problem with the current command is that it doesn't give you any feedback when you add or remove a provider:
```
$ infra providers add okta acme.okta.com foo bar
$ infra providers list
  NAME   URL
  infra
  okta   acme.okta.com
```

The `providers add` command doesn't give any feedback here. It should:

- Provide a success message when a provider is successfully added
- Tell me there is an error if 1. acme.okta.com could be reached, and/or 2. the login wasn't successful testing out the provider (and set the appropriate exit code so that this can be scripted)

The same is true for `providers rm`. The case sensitivity in my opinion is a red herring. The real problem should have been:
```
$ infra providers remove Okta
error: couldn't find provider Okta to remove
```

**Comment by dnephin** [comment]
It looks like e203ab17ae914f34f19715b4cb4d5f5daa50b37c added the feedback for `infra provider add`, and d41ba4919355f22862a11925a9810143e4e11c14 added the feedback for `infra provider remove`.

Should we close this issue (since there should be enough feedback from the CLI to address the original issue), or should we keep it open to discuss case sensitivity in the API?

I agree with Patrick here, I'm weary of making the API case insensitive.  There are basically two options to do this:

1. lowercase everything when we receive it, which is not a great UX. If someone submits something with uppercase, we should keep it.
2. keep the case, but make sure that every single place we compare names we are doing so case insensitive. This can be a challenge in DB queries, and is easy to forget and get wrong.

I think the approach of keeping case sensitivity and giving clear feedback to the user is the best option.

**Comment by jmorganca** [comment]
@dnephin makes sense – this is the way to go
