### ISSUE TITLE
api.Time does not get serialized properly if marshalled by value

### ISSUE THREAD

**Issue by mxyng** [infrahq/infra#1614]
## Describe the bug

A resource with an `api.Time` field doesn't get properly serialized to JSON when it's passed into `json.Marshal` by value. `MarshalJSON` erroneously produces `{}` instead of the time. Passing the resource in by reference works as expected.

## Expected behavior

Time field should be serialized correctly regardless if the resource is passed by value or by reference.

## Environment

```
$ infra version
Server: 0.10.2
```

**Comment by dnephin** [comment]
I believe this is because the `Time.MarshalJSON` method has a pointer receiver, and not a value receiver.  

If a struct method uses a value receiver (not a pointer) then both a pointer to that struct, and the struct value itself implement the interface.
But if a struct method uses a pointer receiver, then only a pointer to that struct implements the interface.

I think that's what is happening here, but it surprised by because the field wasn't being passed to `json.Marshal` directly. It was a  a `api.Provider` that had fields of `api.Time`, and when a pointer to `api.Provider` was marshaled it worked. I did not realize those rules about method receivers applied when the struct was a field on another struct as well.
