### ISSUE TITLE
api: errors are not human readable

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#1686]
Examples:
* `409`: `{"code":409,"message":"duplicate record: UNIQUE constraint failed: providers.name"}` – should be `a provider with this name already exists`

**Comment by dnephin** [comment]
I think the fix for this will not be entirely in the API. We'll want to extract the data out of the driver-specific errors (pgerr, and sqlite3.Error) in the `data` layer, and return our own typed error with the field and entity name extracted to struct fields.

I started that in https://github.com/infrahq/infra/compare/dnephin/data-duplicate-error (along with some cleanup to use our existing helper function more consistently). It's still a work in progress, but I'll be putting it on hold until this issue moves out of the backlog.

**Comment by dnephin** [comment]
https://github.com/infrahq/infra/compare/dnephin/data-duplicate-error does:
* use `handleError` consistently to process all DB errors
* parse both the postgresq and sqlite errors

Still TODO:
* write a test that parsing a unique constraint error works for both postgres and sqlite
* `UniqueConstraintError` only stores field right now, maybe it should also store the name of the table? Or maybe that information can be added by the caller, not sure. We can also rename this type to something else and change the error message. I didn't spend much time on the naming yet. I think we probably do want to keep this error in the `data` package.
* update `sendAPIError` to understand this error and create the structure for `api.Error.FieldErrors`. I guess this would look like validation errors, and use `errors.As` to get access to the fields.
* any places that currently check for `errors.Is(err, internal.ErrDuplicate)` may need to be updated to check for `data.UniqueConstraintError`
* likely we can delete `internal.ErrDuplicate` since it won't be used anymore after these changes.

**Comment by jmorganca** [comment]
Linking here since there's valuable input: [2008](https://github.com/infrahq/infra/issues/2008)
