### ISSUE TITLE
Users don't exist and can't be edited even though they've logged in via an identity provider

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#2144]
To reproduce:

1. User logs in via an identity provider

```
$ infra users list
  jeff@infrahq.com             just now 
```

2. Editing a password doesn't work:
```
$ infra  users edit jeff@infrahq.com --password
  Enter a new password (min. length 8):
? Password: ********
? Confirm Password: ********
ERROR  existing credential: record not found
```

3. Creating a user still works, even though one existed:
```
$ infra users add jeff@infrahq.com
Added user "jeff@infrahq.com"
Password: <redacted>
```

What would make more sense to customers:

1. If a user logs in via an IDP, they exist as a user in our system
2. They can have their password set
3. Creating another user fails since they already exist

**Comment by ssoroka** [comment]
> Creating another user fails since they already exist

I don't think we can do this. Consider the case where a user is added via multiple idps (non-local). If this was to happen through the API, both would need to be able to call _create_ and _delete_ API endpoints for their own provider, but the actual user record wouldn't delete until the last provider deleted the user.  Today we avoid this by not going through the api for IDPs, but I think the point is still valid (eg a company could implement their own IDP to connect up to their custom identity service). If both IDPs need to be able to create and delete, they're not editing the actual user, and we can't break their workflow because a separate IDP has added the user already. Each IDP has a self-consistent view of the world and the API should uphold that. This means all user endpoints succeed based on that particular IDP's view of the world. If anything's missing, it's the ability to specify a non-infra idp.

**Comment by ssoroka** [comment]
discussed and resolved this in https://github.com/infrahq/infra/pull/2287/
