### ISSUE TITLE
allow connector to be forcefully deleted 

### ISSUE THREAD

**Issue by kimskimchi** [infrahq/infra#2261]
## Is your feature request related to a problem? Please describe.

If user really is sure that they want to delete the connector user, they can do so with `--force` flag. 

EG 
```dev users remove connector
The "connector" user cannot be deleted, as it is not modifiable.
```

can now be overridden: 
```dev users remove connector --force
Removed user "connector"
```

## Additional context

Related: #2210

**Comment by mxyng** [comment]
This shouldn't be possible. The connector user is the only user with the correct permissions to perform all actions necessary for a connector to communicate with the server. Remove it will have catastrophic consequences for the deployment.

Instead of forcefully removing the connector users, Infra needs to be rearchitected to not rely on the a connector user. See #2238.

So long as the connector user exists, it should not be removeable
