### ISSUE TITLE
Replace login via access key with specifying access key as an argument or environment variable

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#2286]
Infra's access keys are meant to be used as API keys. They should not be used in the login flow.

1. Remove logging in `infra login` via access key
2. Allow `INFRA_ACCESS_KEY` and `INFRA_SERVER` (or similar) as environment variables
3. Optionally allow `--access-key` as a global flag for the CLI – although we shouldn't encourage using access key in plain text

**Comment by dnephin** [comment]
As part of this, I guess we should add cli flags and env var support for reading the infra server and infra hostname? Otherwise the CLI won't be usable with api keys.

I guess `mustBeLoggedIn` will need to be aware of those settings (to not error if they are set), and `defaultAPIClient` will need to be able to read those options to construct the API client.
