### ISSUE TITLE
Add API reference to documentation

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#2427]
We have an OpenAPI document, we need a good way to render it into a page on our website.

**Comment by dnephin** [comment]
#2428 removes `docs/api/openapi3.json` because we don't have a good way to updated it post-release. The file is still there in `testdata` so that any API changes will be visible in the PR that makes the change, and so that we don't run into surprises when we try to release.

As part of this change we'll need to generate the openapi doc before publishing the docs.
