### ISSUE TITLE
Provide detailed logging for an user request 

### ISSUE THREAD

**Issue by yeshwanth1312** [infrahq/infra#3031]
## Is your feature request related to a problem? Please describe.

We would like to see clear logging when user logs in 

## Describe the solution you'd like

Example of sample log 

```userId=*** orgId=1 uname=admin@example.com t=2022-08-26T16:31:16.208480891Z level=info msg="Request Completed" method=POST path=***** ```

## Environment Details

```
$ infra version
```

```
$ kubectl version
```

**Comment by dnephin** [comment]
Thank you for raising this issue! There is already logging in place that should indicate a login, but we are missing some of these details.

We'll need to:
* add a `msg` so that the logs are easy to find, currently we use an empty string
* add the userID and probably orgID to the log message

I don't think we can include the user email address in the logs, as that could be considered personal identifiable information that has to be managed careful. Logs are generally difficult to prune so we shouldn't include it in logs. Hopefully the userID will work well enough. The API should allow you to lookup the email address from an ID.
