### ISSUE TITLE
Simplify access key query logic related to expiry time

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#3118]
Related to https://github.com/infrahq/infra/pull/3094#discussion_r961690050

Currently to exclude expired access keys from `ListAccessKeys` we have to check 6 conditions:
* expiry > now
* expiry not null
* expiry not zero
* extension deadline > now
* extension deadline not null
* extension deadline not zero

However in `RemoveExpiredAccessKeys` all we do is check `expires_at <= ?`, which it turns out should be sufficient, because:

1. neither field can be null. If they had null values then our code would refuse to scan them into a `time.Time`
2. the extension deadline does not matter. It can actually be a time later than `expires_at` (I believe) , because we keep adding `extension` time to it, without checking if that time is greater than the expiry (which is ok because expiry always take precedence). We even have code that relies on this now (https://github.com/infrahq/infra/pull/3654#discussion_r1024218163).
3. `expires_at` must always be set, we enforce a non-zero value when we create an access key

So give that, we should be able to simplify the query logic to simply `expiry > now AND extension_deadline > now`. Although we do need to make sure that we're always setting `extension_deadline == expiry` instead of leaving it 0.

**Comment by mxyng** [comment]
We need to clarify the semantics of extension deadline. As implemented today, the extension deadline is a time window within which the access key must be used otherwise it gets invalidated. This doesn't align with my idea of what an extension deadline means. In my mind, the extension deadline, or maybe some other name, is an extension of key lifetime whenever it's used.

Example, a key with an expiry of 1d and an extension of 1h will increase its expiry by 1h every time the key is used. The key will never expire as long as it's used within a 1h period. If the key isn't used within the 1h window, it expires and the client must get a new key.

In this interpretation, the extension deadline could be null/zero but it should not be part of the `is_expired` check since the extension deadline updates the `expires_at` value.

**Comment by dnephin** [comment]
That improvement is tracked in #2089. I agree we should look at improving the terminology here, and it's good to call out that these two issues could impact each other.
