### ISSUE TITLE
Switching between infra organizations leaves kubeconfig set to a non-existent context

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#3344]
To reproduce:

1. Run `infra login` against a server / organization
2. Run `infra use` to switch kubernetes contexts
3. Run `infra login` against a new server / organization

The user's Kubeconfig is set to a non-existent kubernetes context

**Comment by dnephin** [comment]
I guess the non-existent kube context is the one from the previous `infra use`.
 
 #3466 might be one option to address this.
 
Another option might be to somehow identify which server+organization each of the infra contexts belong to, so that `use` doesn't erase entries related to other servers and orgs. I'm not sure what options kubeconfig has to annotate each context.
