### ISSUE TITLE
Delete grants for destination when destination is deleted

### ISSUE THREAD

**Issue by BruceMacD** [infrahq/infra#3561]
## Describe the behavior
When a destination is removed:
`infra destinations rm example`

The destination is removed but grants which control access to that destination are not removed. 

## Expected behavior

When a destination is removed we remove the associated grants.

**Comment by dnephin** [comment]
I think on the surface this makes sense, but there are some other things to consider.

Right now we allow grants to be created for a destination before the destination exists. Should we still allow that if we are deleting grants with a destination? Maybe we should create the destination when the first grant for it is created?

We've talked some about automatically removing a destination after it's inactive for some time (#2440). I think if we remove grants along with the destination then we can never automatically remove a destination based on inactivity, because an outage could wipe up a bunch of grants, which would force someone to recreate them all (really bad UX!).

Personally I'm a fan of this approach:
1. Create the destination with nothing but a name when the first grant for the destination is created
2. Update the destination when the connector connects
3. Never automatically remove a destination based on LastSeenAt,  require a user to explicitly remove the destination
4. Remove all the grants for the destination when the destination is removed

I think as a side-effect of this approach we could use the destination ID in the grants table (instead of the destination name), which would make it easier to join to other tables.

**Comment by dnephin** [comment]
Fixed by #3561
