### ISSUE TITLE
UI should not show browser session access key and allow deletion

### ISSUE THREAD

**Issue by mchiang0610** [infrahq/infra#3661]
The UI should not show browser session access key and allow deletion. 

![image](https://user-images.githubusercontent.com/3325447/202499068-2d3ad116-ecd6-42b3-9d40-ce3ec4321eaf.png)

**Comment by mchiang0610** [comment]
related to #3593

**Comment by dnephin** [comment]
I opened #3681 which changes the API to refuse the delete if the access key being deleted is the same one that was used to authenticate the request. That change probably doesn't address this issue entirely (because we may also want to hide the button in the UI), but it's probably a nice safeguard to prevent other API clients from making the same mistake.
