### ISSUE TITLE
Better error message content for API errors

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#3814]
Errors in Infra currently have the following format:

```json
{
  "code": 400,
  "message": ".. long error message"
  "fieldErrors": [{
    "fieldName": "password",
    "errors": ["too short", "not enough special characters"]
}
```

However, in various API `POST` endpoints, the error messages surfaced use the Go error wrap formatting, which isn't obvious to users what it means.

**Comment by dnephin** [comment]
I don't think we can reliably customize every error message that comes out of the API. The Go convention of wrapping errors works well in general, but it's tricky to get the wrapping message just right in all cases. Attempting to write a custom message for all cases is likely to result in error messages that don't contain enough information because we over-generalize the error.

Do we have examples of specific error message that we've found do not read well?

I think this issue is not actionable unless we know which specific cases need to be improved.
